language: node_js
node_js:
  - "stable"

services:
  - docker

cache:
  directories:
    - node_modules

script:
  - npm run build
  - docker build -t inseefrlab/inspacy-ui .

deploy:
  skip_cleanup: true
  provider: script
  script:
    echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
    && docker push inseefrlab/inspacy-ui
  on:
    branch: master
env:
  global:
    - secure l+EYpZU/Ii2UPmYDY6Hqu5GnRNAXwb4KbjttSzasjbdMHnk+/Gubx9PNwGmRfQflMhhGlYdBAuYkXAnJxeQlj3ccC2127eQEFr8H0zE4cdAMIiEaNJ1kmZ4rBYuEu73CM4XSqLCIqtXftdoR2U2BUfwcbXH0rVflv3OYXvL6NzowgS2yrQGPCbZFTFb3PtxGTOewzcj6JO6APOOMYRgfTyAV9Z61n3XJwf5c56Y4YohFGb9DNyUPqIfZ3fvqo/RiiuttaO0tWXeGRT/+g3oWo1DDmBwf6C/FELWUM6gt1s3gYyFAbZaorEdEaIfkmVmonWoJt2YWoUWW4qmx5UiOT5T39RV1tUe8heVqPcCjPyf1EJjiIPC56nP7zcEYeyxQWRR4C8+nKKKavlVUz3qsnKuZrnvNu7X6fa39X3R8rjWBMWqdkWpWlQizdkhW7hvvJPGA7l0w+3KoZK6mYiV5+e3ZWTJelcO0++gChECxHjh2ndy5E2DstJkVJ0lm+LcqNsMEUmcBkelzKVpeskEInSwTtBVNQBnxXo6D3O6n/36wb6hbvKk/HivCd5hYGkajd8yncCpSgNUZN5pLEqI6zdYa6BdSxsXo5FmCnItvvvW2O4W/V5IB4TMg0GlGchS2U7SU1TtQObfxk28ipVsk+tLJ6VH6C57i9d4EO18aqn4=
    - secure TWWr+rdQPmUjTwwTp1v6Y/Az5lt12u64SfeDFMSIkggwfVvRpJXUbcOfpMF2DpLKgcJ7mJzWbWoPMS39vcYcIWfomnnmEPHpeUyA0/1919NBkseiQ7LTcoiOvyTRYuwOms8qQP/KDOXgTFIsMWXYj1+PVDwh58A6T9KO8RfsKKRO57G9DWCyuL1cCQWKuDgYweGBUsIu+ypXToq1NmSNFoAzyzWvAWn3r+K5z//s6zA5hpWTYK9XhzIAqoRGnjN7vIXFnEyWc2YqpEaqNzqBSJWmGpnS5qkdH5yjmYbSo5MZ0CfMrqr76yJjApxibC9cWo51RoMn4Ru7LmVhiT/LLnNyQgrp/e8DzJ7Dt+eQBH/ZPe5jydKXp1iL8nxPosHORoQAsRiB96blDMzNK7AAqnuYoufBE5joV3OeaUJFaCcQpBeAPMah1+q0Dq+cIzOtlyocCu5s698FDCFPYUUEsoTfHTM92zjMbYQNHf23fQ1bBXysT9o2F68p48fP2z2a9BrI6NTx4a//ro5iyaplR3jYEqkkndwd1jaYvv0ZsEMP7iOYFkpzZk2d7qFZU48ERUET75ocF7zvT9rre76LHWBStSe5N2ZiwOlTwyeH3Hhm3atLIaNHNG6zYUt6Hy/jgiqZnuTqfsRduDrsYxDjN5SLsXTljcEKvAGWIZK9cJs=
